:icons: font
:source-highlighter: highlightjs
:highlightjsdir: hljs
:highlightjs-theme: solarized-light

:toc: left

= AsciiDoc Overview

http://asciidoctor.org/docs/what-is-asciidoc/[Why AsciiDoc?]

It should be easy to do things the right way by default - and this applies to technical writing and documentation too!

Just like markdown, it's easy to read and write AsciiDoc using plain text

Unlike markdown however, AsciiDoc supports far more complex formatting rules, and can include snippets of documentation from arbitrary other files, such as source code.

This is important - the closer documentation lives to the code it documents, the more likely it is to be read and kept up-to-date. Tools like javadoc already follow this principle; AsciiDoc makes it easy with any ecosystem.

== Setup

=== Ruby-based

****
Pros::
* Easier to install system-wide
* Better compatibility with third-party extensions
** and wrappers like `asciidoctor-confluence`

Cons::
* Ruby environments require more setup
* Lack of easy live-reloading for local editing
****

.Rendering commands
[source,bash]
----
asciidoctor FILE.adoc
open FILE.html
----

==== Configuration files

.Gemfile
[source,ruby]
----
include::Gemfile[]
----

=== Node.js based

****
Pros::
* Easier to bootstrap
* Much easier to do live-reloads locally

Cons::
* npm ecosystem is fragile
* not compatible out-of-the-box with non-js extensions
** https://github.com/asciidoctor/asciidoctor.js/issues/84[workarounds may exist however]
****

.Render commands
[source,bash]
----
#Setup
source nodew #Optional - use if you don't have node locally
npm install

#Render the document directly
gulp adoc

#Automatically render and reload the document in a local browser
gulp watch connect
open http://localhost:8080/DOCUMENT_PATH.html
----

==== Configuration files

.package.json
[source,json]
----
include::package.json[]
----

.gulpfile.js
[source,javascript]
----
include::gulpfile.js[]
----

== Syntax Highlighting

`asciidoctor` has pluggable syntax highlighting:

=== coderay

Pros::
* Gem-based, minimal configuration needed
* Works with most backends

Cons::
* No customization or styling options
** Built-in coloring isn't the best
* More limited language support

=== highlightjs

Pros::
* Themable, with solarized themes available
* Support for more languages

Cons::
* Requires more setup
* Only works with the HTML5 backend since it's javascript
* Can't easily embed the JS/CSS into the html file
